import {
  CssIcon,
  ExpressJsIcon,
  GitIcon,
  GithubIcon,
  HtmlIcon,
  JavascriptIcon,
  MongodbIcon,
  MongooseJsIcon,
  NextjsIcon,
  NodejsIcon,
  NpmIcon,
  ReactIcon,
  ReduxIcon,
  SocketIoIcon,
  SwaggerIcon,
  TailwindCssIcon,
  ViteIcon,
} from "@/src/components/icons/web";

export const Icons = {
  html: HtmlIcon,
  css: CssIcon,
  javascript: JavascriptIcon,
  react: ReactIcon,
  redux: ReduxIcon,
  nextjs: NextjsIcon,
  nodejs: NodejsIcon,
  express: ExpressJsIcon,
  mongodb: MongodbIcon,
  mongoose: MongooseJsIcon,
  socketio: SocketIoIcon,
  npm: NpmIcon,
  vite: ViteIcon,
  tailwind: TailwindCssIcon,
  git: GitIcon,
  github: GithubIcon,
  swagger: SwaggerIcon,
};
